### ISSUE TITLE
AE2 Chunk build failed

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#432] opened 2024-04-19 21:32 UTC
### Your GTNH Discord Username

skproch

### Mod Version

angelica-1.0.0-alpha38

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

While flying in my base get aqua screen and chunk build failed

Crash: https://mclo.gs/CFl3XhY
Log: https://mclo.gs/MVBOJUr

### Mod List or GTNH Pack Version

GTNH 2.6.0-beta3

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment] 2024-04-19 22:24
This likely needs a null check guard in ae2, and a sanity check to see if it's a thread saftey issue or something else.

**Comment by SKProCH** [comment] 2024-04-26 15:38
@mitchej123 i've updated to AE2 350 version, and got this crash.

Crashlog: https://mclo.gs/1CwtPBB  
Log: https://mclo.gs/aeue8ev

**Comment by Cleptomania** [comment] 2024-04-29 04:51
I'll leave this open for the moment, but we are also tracking this here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16075

Seems a fairly wide-spread issue since releasing 2.6.0.

I've so far been unable to reproduce the crash, even with worlds sent by players where it's verified to be happening.

**Comment by norbby42** [comment] 2024-05-01 03:37
In my world, this did not happen in 2.6.0-beta3, but happens with 2.6.0 release.  Hopefully that helps narrow it down.

[crash-2024-04-30_23.28.21-client.txt](https://github.com/GTNewHorizons/Angelica/files/15173191/crash-2024-04-30_23.28.21-client.txt)

**Comment by biosoup** [comment] 2024-05-01 04:44
Same issue here, in fresh install of 2.6.0. with transferred save (based on instructions from Wiki, was changing launchers to Technic).

[crash-2024-05-01_06.40.07-client.txt](https://github.com/GTNewHorizons/Angelica/files/15173829/crash-2024-05-01_06.40.07-client.txt)

**Closed** 2024-05-18 22:59 UTC
