### ISSUE TITLE
Angelica flickering and light bug with resource pack

### ISSUE THREAD

**Issue by elitecat** [GTNewHorizons/Angelica#454] opened 2024-04-29 15:19 UTC
### Your GTNH Discord Username

elitecat

### Your Pack Version

2..6.0

### Your Server

sp

### Java Version

Java 8

### Type of Server

None

### Your Expectation

After joining the server the boxes and heads flicker I did that and then saw it
Showing screenshots because of flickering is rather meh
here the video: https://drive.google.com/file/d/1uxB1irrJUBeEhpb7bt90Q6bVEj9wrxQH/view?usp=sharing

### The Reality

Since the modpack version 2.6.0 the chests and heads and the trophies have been flickering. In the beta 2 of 2.6.0 there were no such problems. I play with the resource pack offered on the gtnh website

### Your Proposal

problem just exists without having done anything except using a resource pack that didn't cause any problems in previous versions

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by YamiKami-Sama** [comment] 2024-04-30 09:51
Got the same in my thaumcraft room

**Comment by tomasz-brak** [comment] 2024-04-30 17:22
[Replay 2024-04-30 18-59-15_1.webm](https://github.com/GTNewHorizons/Angelica/assets/62989490/e1c83a28-e22f-4089-925a-fd03626b022a)
Got the same thing but much more intense, on java 21, rtx 2060, GTNH 2.6.0, angelica Alpha 40
Then the game crashes with this log: https://mclo.gs/qqGLSRs

**Comment by mitchej123** [comment] 2024-04-30 17:24
Flickering is likely unrelated to the crash.

The crash is Ae2, which is being worked on.
```
Caused by: java.lang.IllegalArgumentException: Cannot create a wrapper icon with a null icon.
    at appeng.client.texture.OffsetIcon.<init>(OffsetIcon.java:27)
    at appeng.parts.networking.PartCableSmart.renderStatic(PartCableSmart.java:224)
    at appeng.client.render.CableRenderHelper.renderStatic(CableRenderHelper.java:57)
    at appeng.parts.CableBusContainer.renderStatic(CableBusContainer.java:7[31](https://mclo.gs/qqGLSRs#L31))
    at appeng.client.render.blocks.RendererCableBus.renderInWorld(RendererCableBus.java:47)
```

**Comment by tomasz-brak** [comment] 2024-04-30 20:35
is there any data i could provide to help diagnose the filickering? it is really making everything unplayable

**Comment by tomasz-brak** [comment] 2024-04-30 20:49
ah and also btw the flickering occurs only on the new modpack version, on 2.5.1 it was not present, at least for me

**Comment by SKProCH** [comment] 2024-05-03 16:31
This is probably related to runic matrix. Seems like if matrix is present all such entities (matrix, pillars (not the pedestals), bm altar) will flicker.

**Comment by kofteistkofte** [comment] 2024-05-06 20:26
[angelica_flicker.webm](https://github.com/GTNewHorizons/Angelica/assets/906680/0dc776e0-055b-4803-bc4b-6c0c3852ac16)

Same thing happening to me too.
GTNH 2.6.0
Angelica 1.0.0-alpha43 (happens on alpha 40 and 42 too)
Linux kernel 6.8.9
Java 17 (Built-in jvm of Prism Launcher Flatpak)
AMD RX 7900 XT with amdgpu drivers
Wayland

**Comment by Caedis** [comment] 2024-05-06 20:32
Duplicate of https://github.com/GTNewHorizons/Angelica/issues/421

**Closed by Caedis** 2024-05-06 20:32 UTC
