### ISSUE TITLE
Game stuck at loading screen

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#186] opened 2024-01-13 22:29 UTC
### Your GTNH Discord Username

SKProCH

### Mod Version

1.0.0-alpha14

### Java Version

Java 21

### Bug Report

1.0.0-alpha12 - works fine
When I try to use 1.0.0-alpha13/1.0.0-alpha14 I get stuck at loading screen (different each time):
![image](https://github.com/GTNewHorizons/Angelica/assets/29896317/d0952e37-64b2-4bd3-9a31-0693668546ab)
Game plays loaded sound but stuck at 
```
Sound engine started
```
in the log.  
Here is the bugged log: https://mclo.gs/wadDroj  
Here is the normal log (with alpha12): https://mclo.gs/Ypk2L34  

If I disable `enableVBO` in the config - it starts working as expected

### Mod List or GTNH Pack Version

GTNH 2.5.1
LWJGL3ify, Hodgepodge, CodeChickenCore/Lib, Neodymium updated to latest versions

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by PlayfulPiano** [comment] 2024-01-13 23:16
duplicate of https://github.com/GTNewHorizons/Angelica/issues/162#issuecomment-1890417927

**Closed** 2024-01-13 23:17 UTC
