### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by BlueHero233** [GTNewHorizons/Angelica#617] opened 2024-09-01 14:40 UTC
### Your GTNH Discord Username

BlueHero233

### Mod Version

1.0.0-beta4

### Java Version

Java 17

### Graphics Card Vendor

AMD/ATI

### Bug Report

[fml-client-latest.log](https://github.com/user-attachments/files/16829303/fml-client-latest.log)

### Mod List or GTNH Pack Version

GTNH 2.6.1
Angelica 1.0.0-beta4
GTNHLib 0.4.10-pre

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Lyfts** [comment] 2024-09-01 14:43
Update amazing trophies to https://github.com/GTNewHorizons/Amazing-Trophies/releases/tag/1.2.2

Also duplicate of https://github.com/GTNewHorizons/Angelica/issues/613 & https://github.com/GTNewHorizons/Angelica/issues/597 and probably a few others.

**Closed by Lyfts** 2024-09-01 14:43 UTC
