### ISSUE TITLE
Blocks lighting issue

### ISSUE THREAD

**Issue by Darkenlord1** [GTNewHorizons/Angelica#576] opened 2024-07-31 04:53 UTC
### Your GTNH Discord Username

ljedamos

### Mod Version

1.0.0-beta3

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

After updating to beta 3 lighting on casings became slightly off. They are now ~blackface~ slightly darker than other multiblock blocks.
![image](https://github.com/user-attachments/assets/6e43a338-f3aa-4ca3-895c-85b5453af160)

### Mod List or GTNH Pack Version

2.6.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Darkenlord1** [comment] 2024-07-31 04:56
F3 + A doesnt help. 
This persist with and without nightvision buff. Hovewer if disable smooth lighting and nightvision, they are completely black, atleast stainless steel ones
![image](https://github.com/user-attachments/assets/078d1104-206b-4b79-b39b-211b02594ed3)

**Comment by Darkenlord1** [comment] 2024-07-31 05:02
With smooth lighting - 
Affected sides are (slightly darker):
bottom, west, east.

up, south and north are displayed fine.

Without it is just a mess (coil blocks too):
![image](https://github.com/user-attachments/assets/084594cd-5e02-4552-9658-f66cfc5ebbbc)

**Comment by Darkenlord1** [comment] 2024-07-31 05:06
Stone block, AE2 wireless connectors, plascrete blocks, dire autocrafting benches affected too.
![image](https://github.com/user-attachments/assets/6bc1a36e-2ff0-4421-9f32-dc56d4a7ff41)

**Comment by Cleptomania** [comment] 2024-07-31 05:38
I have some ideas for this, it's definitely related to my beta3 changes. I will see if I can figure out a fix tomorrow. If not we can probably roll-back the sodium AO enforcement in a beta4 until we can figure out how to properly handle ISBRH's trying to use piggyback on vanilla AO.

**Comment by Jerome226** [comment] 2024-07-31 06:19
> I have some ideas for this, it's definitely related to my beta3 changes. I will see if I can figure out a fix tomorrow. If not we can probably roll-back the sodium AO enforcement in a beta4 until we can figure out how to properly handle ISBRH's trying to use piggyback on vanilla AO.

**I can infact confirm it's caused by beta3 changes.**

beta.3
![2024-07-31_02 16 54](https://github.com/user-attachments/assets/ab56e642-6047-48eb-93a4-0630976b0409)

beta.2
![2024-07-31_02 17 54](https://github.com/user-attachments/assets/0377f980-c96f-4ea0-bac2-0a7fe4914fe4)

**Comment by Cleptomania** [comment] 2024-08-20 23:58
I believe this was fixed with beta4, if I turn out to be wrong about that, feel free to re-open.

**Closed by Cleptomania** 2024-08-20 23:58 UTC
