### ISSUE TITLE
Crash while rendering chunks of toxic everglades

### ISSUE THREAD

**Issue by Wacchi-Lorie** [GTNewHorizons/Angelica#404] opened 2024-03-27 13:05 UTC
### Your GTNH Discord Username

wacchi_lorie

### Mod Version

1.0.0-alpha35

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

crash while rendering new chunks of toxic everglade, rebooting dont recover and this is the first time i enter toxic everglade
[crash-2024-03-27_20.56.49-client.txt](https://github.com/GTNewHorizons/Angelica/files/14773668/crash-2024-03-27_20.56.49-client.txt)

### Mod List or GTNH Pack Version

GTNH 2.5.1
Crash report following

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by madmacf** [comment] 2024-04-09 13:51
Same here on 2.6.0 beta2.
Crashes after a few seconds when flying around.
[crash-2024-04-09_15.46.24-client.txt](https://github.com/GTNewHorizons/Angelica/files/14919370/crash-2024-04-09_15.46.24-client.txt)

**Comment by Wacchi-Lorie** [comment] 2024-04-29 08:54
issue persists with 2.6.0 release

**Comment by Lyfts** [comment] 2024-05-04 19:32
Here's a log from GT++ dev env with the same result but no mention of any cofh asm
[crash-2024-04-27_21.48.53-client.txt](https://github.com/GTNewHorizons/Angelica/files/15210762/crash-2024-04-27_21.48.53-client.txt)

**Comment by chochem** [comment] 2024-05-05 20:27
have your tried without angelica to see if it works then? just to be sure its the cause as the trace isnt really conclusive.

**Comment by Lyfts** [comment] 2024-05-05 20:32
With angelica I would crash within 5 minutes (usually much shorter) of being in the everglades and without angelica I managed to spend a couple hours without crashes whilst testing things for https://github.com/GTNewHorizons/GTplusplus/pull/877

**Comment by Dream-Master** [comment] 2024-05-11 08:44
@Lyfts so is this fixed with the GT pr ?

**Comment by Lyfts** [comment] 2024-05-11 09:03
No it still crashes with Angelica

**Comment by Dream-Master** [comment] 2024-05-11 09:11
so a new Angelic version not fix it ?

**Comment by Dream-Master** [comment] 2024-05-11 11:19
@Wacchi-Lorie

**Comment by Caedis** [comment] 2024-05-13 18:20
Fix in alpha48

**Closed by Caedis** 2024-05-13 18:20 UTC
