### ISSUE TITLE
Crash on server join.

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/Angelica#405] opened 2024-03-28 06:45 UTC
### Your GTNH Discord Username

Axiflare

### Mod Version

angelica-1.0.0-alpha35

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14785023/fml-client-latest.log)

### Mod List or GTNH Pack Version

2.5.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Axiflare** [comment] 2024-03-28 06:45
First time submitted a crash in a long time, sorry if I missed something

**Comment by mitchej123** [comment] 2024-03-28 06:51
```
java.lang.ClassCastException: class cpw.mods.fml.client.registry.RenderingRegistry cannot be cast to class com.gtnewhorizons.angelica.mixins.interfaces.IRenderingRegistryExt (cpw.mods.fml.client.registry.RenderingRegistry and com.gtnewhorizons.angelica.mixins.interfaces.IRenderingRegistryExt are in unnamed module of loader net.minecraft.launchwrapper.LaunchClassLoader @6d21714c)
    at com.gtnewhorizons.angelica.rendering.AngelicaBlockSafetyRegistry.populateCanRenderOffThread(AngelicaBlockSafetyRegistry.java:35)
    at com.gtnewhorizons.angelica.rendering.AngelicaBlockSafetyRegistry.canBlockRenderOffThread(AngelicaBlockSafetyRegistry.java:27)
    at com.gtnewhorizons.angelica.proxy.ClientProxy.lambda$worldLoad$0(ClientProxy.java:85)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.gtnewhorizons.angelica.proxy.ClientProxy.worldLoad(ClientProxy.java:82)
```

**Comment by mitchej123** [comment] 2024-03-28 06:57
This was fixed in https://github.com/GTNewHorizons/Angelica/pull/403. The problem is you've got the sodium backport module disabled, which is responsible for most of the fps gains...

**Closed** 2024-03-28 06:58 UTC

**Comment by Axiflare** [comment] 2024-03-28 10:08
Whoops, I'm an idiot. Completely forgot I tried disabling Sodium to try to fix a crashloop caused by something else. I'll report back if I get a crash after re-enabling it.

**Comment by Axiflare** [comment] 2024-03-28 10:54
Hope this helps, 3 seemingly random crashes and then a crash loop. Worked for about an hour though!
[fml-client-latest.log](https://github.com/GTNewHorizons/Angelica/files/14788063/fml-client-latest.log)

**Comment by mitchej123** [comment] 2024-03-28 15:44
Looks like a crash with bartworks that was fixed in https://github.com/GTNewHorizons/bartworks/pull/1

Your version is significantly older -- Use the nightlies, Cherry pick the commit, or use the release of Angelica before whitelisting bartworks/gregtech again
