### ISSUE TITLE
Enderio - Farming Station texture disappear

### ISSUE THREAD

**Issue by i24E** [GTNewHorizons/Angelica#349] opened 2024-02-29 09:57 UTC
### Your GTNH Discord Username

24E#1105

### Mod Version

alpha30

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

I have switched image quality, but there has been no change.
<img width="1280" alt="391DED9459EB7A07AAF54D921F2F60C4" src="https://github.com/GTNewHorizons/Angelica/assets/86151680/005b3faa-3b45-45ec-aedc-daf98cdc92c7">

### Mod List or GTNH Pack Version

gtnh2.5.1 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Dynamiczbee** [comment] 2024-02-29 15:59
This is a duplicate of #203

**Closed** 2024-03-05 03:02 UTC
