### ISSUE TITLE
Fast leaves and unrelated Thaum warp mushroom effect

### ISSUE THREAD

**Issue by Abalieno** [GTNewHorizons/Angelica#96] opened 2023-12-29 00:16 UTC
### Your GTNH Discord Username

Trystero

### Mod Version

angelica-1.0.0-alpha10

### Java Version

Java 21

### Bug Report

As written on Discord.

Leaves options do nothing, both sodium screen and notfine screen. Only setting affecting leaves seem to be the overall graphic one. Fancy leaves seem to work fine. Whereas "fast" leaves seem to not render properly for modded trees like Thaumcraft.

![jmhj,](https://github.com/GTNewHorizons/Angelica/assets/4656436/979d5d74-6dae-4915-a8fa-e62f5480e50f)

Unrelated, walking on one of those Thaumcraft mushroom has some issues with the rendering of the effect:

![2023-12-29_00 14 15](https://github.com/GTNewHorizons/Angelica/assets/4656436/0ee34f08-00b0-432b-ba57-a946c1e845d7)

### Mod List or GTNH Pack Version

https://github.com/enmumne/Grumpy-GregTech-6

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by Alastors** [comment] 2023-12-29 00:47
1. Not really a thaumcraft issue, those mushrooms cause vanilla nausea effects.
2. Not really one of ours? Unless we have a sodium fork I suppose? But I don’t believe so?
3. Prolly should be 2 separate tickets tbh

**Comment by dvdmandt** [comment] 2023-12-29 01:11
> 2\. Not really one of ours? Unless we have a sodium fork I suppose? But I don’t believe so?

Angelica, the mod this report is about, is largely a Sodium+Iris backport by now. You need to read #upcoming-features more frequently. ;)

**Comment by ah-OOG-ah** [comment] 2023-12-29 01:15
The second appears to be the same as\ [this one](https://github.com/GTNewHorizons/Angelica/issues/80), possibly a general problem with screen warping effects. The fast leaves one may have something to do with Notfine mixins (if enabled) or thaum leaves specifically, IIRC the modded leaves I've seen are fine.

**Comment by mitchej123** [comment] 2023-12-30 22:10
Duplicate of #80

**Closed by mitchej123** 2023-12-30 22:10 UTC

**Comment by Abalieno** [comment] 2023-12-31 14:30
Leaves problem still there.
