### ISSUE TITLE
Laggy movement of xaero's map waypoint beacons

### ISSUE THREAD

**Issue by OlorinIV** [GTNewHorizons/Angelica#223] opened 2024-01-21 16:27 UTC
### Mod Version

1.0.0-alpha15

### Java Version

Java 8

### Bug Report

Angelica + Xaero's Minimap/World Map makes its waypoint beacons move discontinuously when they slide across player view, as if they aren't rendered every frame.

### Mod List or GTNH Pack Version

UniMixin 0.1.15
GTNHLib 0.2.1
CCC/CCL 1.2.0
NEI 2.4.13-GTNH
Angelica 1.0.0-alpha15
Xaero's Minimap 21.10.40
Xaero's World Map 1.14.1.30

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mitchej123** [comment] 2024-02-18 07:28
Try again with the latest alpha (28+) and reopen if still an issue.

**Comment by OlorinIV** [comment] 2024-02-19 15:48
Still present with 28

**Comment by HRudyPlayZ** [comment] 2024-02-29 19:12
Moved the other report here, so it is all in a single thread:

### Your GTNH Discord Username

hrudyplayz

### Mod Version

1.0.0-alpha28

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

As you may know, Xaeros's Minimap is a minimap mod that can add waypoints in-game.
The issue is that the hotbar optimisations seem to also apply to Xaero's waypoints, as they're probably getting rendered as a HUD overlay too. Making the waypoints very laggy and display at 20fps.
It could probably be fixed by making that mixin ignore Xaero's classes.

### Mod List or GTNH Pack Version

- Angelica 1.0.0-alpha28
- GTNH Lib 0.2.9
- UniMixins 0.1.16
- Xaeros Minimap 21.10.31

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Closed** 2024-04-10 16:05 UTC
