### ISSUE TITLE
HUDCaching slows down TC wand focus/goggles lens selection menus

### ISSUE THREAD

**Issue by Evan555alpha** [GTNewHorizons/Angelica#358] opened 2024-03-05 03:02 UTC
### Your GTNH Discord Username

Evan555alpha

### Mod Version

1.0.0-alpha33

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

Title, pretty much. When HUDCaching is enabled, the funny purple circle that appears when going to select a wand focus / goggles of revealing lens, slows to a relative crawl, as though its speed is tied to its framerate. Not unusable, but very noticeable. Toggling off HUDCaching solves the issue.

### Mod List or GTNH Pack Version

GTNH Pack 2.5.1
Hodgepodge 2.4.34
CodeChickenCore/Lib 1.2.0
UniMixins 0.1.16
GTNHLib 0.2.10

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by 3jlowes** [comment] 2024-06-21 19:27
Can confirm this is still happening to me on 2.6.1

**Comment by Caedis** [comment] 2024-06-21 19:55
> as though its speed is tied to its framerate

It actually is after reaching the thaumcraft code

**Comment by OvermindDL1** [comment] 2024-06-21 21:33
> It actually is after reaching the thaumcraft code

Indeed it is, and is always why I unlock my framerate when messing with TC, it's... unpleasant otherwise...

(someone really needs to mixin fix that... hodgepodge maybe?  Who do we need to ping to get a fix into hodgepodge or whatever?  A configurable speed (based on ticks, unbound by fps) would even be far superior, I want to double/triple its speed even when I'm getting 200fps)

**Comment by Caedis** [comment] 2024-06-21 21:59
Maybe @Alastors can help :P

**Comment by 3jlowes** [comment] 2024-06-21 22:04
> Indeed it is, and is always why I unlock my framerate when messing with TC

I'm assuming this is implying higher fps = faster menu?
I have my framerate unlocked, 200 fps and my focus menu is still slow. (with angelica)

Without Angelica, the menu behaves normally.

**Comment by OvermindDL1** [comment] 2024-06-21 22:06
Angelica caches the rendering calls so it doesn't update as rapidly as it would otherwise, which is much better for rendering performance, but bad when a mod does something stupid like lock functionality to re-render times, lol.

**Comment by Alastors** [comment] 2024-06-22 14:40
> Maybe @Alastors can help :P

I mean I can look into it, but my knowledge in rendering as a whole is limited

**Comment by unix-supremacist** [comment] 2024-06-22 14:50
hud cache probably needs to be updated to have its own framerate setting, and generally other caches improved so the framerate by default can be higher to prevent edge cases like this, but yeah the issue is TC being framerate dependent here instead of animating using deltas

**Comment by Cleptomania** [comment] 2024-10-17 04:45
Was this fixed with #562?

**Comment by OvermindDL1** [comment] 2024-10-17 04:46
It's been fixed for me at least in the current GTNH release pack

**Comment by Cleptomania** [comment] 2024-10-17 04:48
I'll close this for now then. If it turns out to still be a problem someone can reopen

**Closed by Cleptomania** 2024-10-17 04:48 UTC
Labels: compat
