### ISSUE TITLE
White items 

### ISSUE THREAD

**Issue by Biskupsky** [GTNewHorizons/Angelica#603] opened 2024-08-15 20:53 UTC
### Mod Version

1.0.0-beta2

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Playing game items icons got white. Didnt happen for hours of playing of Angelica. If it is important it happened when used builder from buildcraft (putting items)

### Mod List or GTNH Pack Version

Playing game items icons got white. Didnt happen for hours of playing of Angelica. If it is important it happened when used builder from buildcraft (putting items)[](url)
![er1 (1)](https://github.com/user-attachments/assets/0d7d2164-1fd4-46ff-b04b-dc7626d5e759)
![er1 (2)](https://github.com/user-attachments/assets/569cef48-b914-4988-868b-8a833d627b68)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Radk6** [comment] 2024-08-17 11:53
Duplicate of #538

**Closed** 2024-08-22 00:27 UTC
